### ISSUE TITLE
Code readability would be helped if CDATA were used

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Medo42/Gmk-Splitter#6]
Would avoid all those annoying `&lt;` and `&gt;` escapes. Might cause `git blame` hell for first and last lines of code, but aside from that, there's nothing to lose.

**Comment by Medo42** [comment]
Closing since I don't see a compelling reason to implement it at this stage. I'm pretty sure we won't reformat GG2 and nobody from a different project is asking for this.

**Comment by TazeTSchnitzel** [comment]
And in any case, what the XML looks like isn't too important, given you can edit in Game Maker.
