### ISSUE TITLE
XML ordering appears to be non-deterministic

### ISSUE THREAD

**Issue by lmanco** [Medo42/Gmk-Splitter#7]
I don't know if this tool is still maintained, but it's great and I've been getting a lot of use out of it. One thing I noticed, however, is that objects in XML sometimes appear to be rearranged for no reason despite the objects not being changed.

Here is what I mean:
![GMK Splitter Non-determinism](http://i.imgur.com/tQd8Auj.png)

I did not touch these objects in GM, but notice that git shows a change in the ordering of objects in the XML. This can be a bit confusing and can occasionally cause merge issues.

**Comment by Medo42** [comment]
I don't think it's worth keeping this open. If you or anyone is still interested in such a commandline switch please tell me.
