### ISSUE TITLE
I can't find the jar file!

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [Medo42/Gmk-Splitter#8]
I went to the folder and couldn't find the jar file.

**Comment by Medo42** [comment]
You probably downloaded the source code. Have a look here for the compiled version: https://github.com/Medo42/Gmk-Splitter/downloads

**Comment by LucianoTheWindowsFan** [comment]
Thank you! I downloaded this cuz I wanted to make a GM81 emulator for either HTML5 or JS.

**Comment by Medo42** [comment]
In that case you should have a look at the LateralGM project this is based on (http://lateralgm.org/), as well as Enigma (https://enigma-dev.org/)

**Comment by Psudonem** [comment]
Hello, I'd love to use your tool, but the link is not working for me! https://github.com/Medo42/Gmk-Splitter/downloads is giving me a 404. 

Thank you.

**Comment by Medo42** [comment]
Hi! Thanks for pointing this out, Github must have finally dropped the old Downloads feature for good.

I've created a Release now with the binary: https://github.com/Medo42/Gmk-Splitter/releases/tag/V0.17

**Comment by Psudonem** [comment]
> Hi! Thanks for pointing this out, Github must have finally dropped the old Downloads feature for good.
> 
> I've created a Release now with the binary: https://github.com/Medo42/Gmk-Splitter/releases/tag/V0.17

Thank you so much!!!
